using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerCam : MonoBehaviour
{
    [Header("R^D用舾卸")]
    public float sensX;   // R^XSD用舾卸
    public float sensY;   // R^YSD用舾卸

    float xRotation;
    float yRotaiton;

    private void Start()
    {
        Cursor.lockState = CursorLockMode.Locked;   // i定滑鼠游嗽诋面中央
        Cursor.visible = false;                     // [藏滑鼠游
    }

    private void Update()
    {
        float mouseX = Input.GetAxisRaw("Mouse X") * Time.deltaTime * sensX;   // 取得滑鼠游说XS移
        float mouseY = Input.GetAxisRaw("Mouse Y") * Time.deltaTime * sensY;   // 取得滑鼠游说YS移

        // 因轭AO的XYS移臃较蛟UNITY是反D的，我要⒒鼠XSD成物件的YS，YSD成XS
        xRotation -= mouseY; // ⒒鼠YS移抵"倒D"^(正正)
        yRotaiton += mouseX;

        xRotation = Mathf.Clamp(xRotation, -90f, 30f); // 限定XSD釉谡30度到90度g(抬^和低^有限制角度)

        transform.rotation = Quaternion.Euler(xRotation, yRotaiton, 0); // O定z影C角度
    }
}
