using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;  // 要有@才能控制文字框

public class Shooting : MonoBehaviour
{
    [Header("⒖嘉锛")]
    public Camera PlayerCamera;
    public Transform attackPoint;

    [Header("子A置物件")]
    public GameObject bullet;

    [Header("枝O定")]
    public int magazineSize;        // O定A可以放多少w子？
    public int bulletsLeft;         // 子有多少w？(如果]有要y，你可以O定成 Private)
    public float reloadTime;        // O定QA所需要的rg
    public float recoilForce;       // 反作用力

    bool reloading;             // 布林担Υ媸遣皇钦在QA的B？True：正在QA、False：QA的幼饕呀Y束

    [Header("UI物件")]
    public TextMeshProUGUI ammunitionDisplay; // 量@示
    public TextMeshProUGUI reloadingDisplay;  // @示是不是正在QA？

    public Animator animatorObject;  // 赢播放器M件

    private void Start()
    {
        bulletsLeft = magazineSize;        // [蛞婚_始AO定槿MB
        reloadingDisplay.enabled = false;  // @示正在QA的字幕[藏起

        ShowAmmoDisplay();                 // 更新量@示
    }

    private void Update()
    {
        MyInput();
    }

    // 方法：y玩家操作B
    private void MyInput()
    {
        // 判啵河]有按下左I？
        if (Input.GetMouseButtonDown(0) == true)
        {
            // 如果有子，K且]有正在重b子，就可以射
            if (bulletsLeft > 0 && !reloading)
            {
                Shoot();
            }
        }

        // 判啵1.有按下RI、2.子盗康挽A鹊量、3.不是QA的B，三l件都M足，就可以QA
        if (Input.GetKeyDown(KeyCode.R) && bulletsLeft < magazineSize && !reloading)
            Reload();
    }

    // 方法：射粑淦
    private void Shoot()
    {
        Ray ray = PlayerCamera.ViewportPointToRay(new Vector3(0.5f, 0.5f, 0));  // z影C射出一l射
        RaycastHit hit;  // 宣告一射酎c
        Vector3 targetPoint;  // 宣告一位置c担到r候如果有打到|西，就存到@

        // 如果射有打到具渑鲎搀w的物件
        if (Physics.Raycast(ray, out hit) == true)
            targetPoint = hit.point;         // ⒋虻轿锛的位置c存M targetPoint
        else
            targetPoint = ray.GetPoint(75);  // 如果]有打到物件，就以L度75的末端c取得一c，存M targetPoint

        Debug.DrawRay(ray.origin, targetPoint - ray.origin, Color.red, 10); // 出@l射

        Vector3 shootingDirection = targetPoint - attackPoint.position; // 以起ccKc之g牲c位置，算出射的方向
        GameObject currentBullet = Instantiate(bullet, attackPoint.position, Quaternion.identity); // 在攻酎c上面a生一子
        currentBullet.transform.forward = shootingDirection.normalized; // ⒆w行方向c射方向一致

        currentBullet.GetComponent<Rigidbody>().AddForce(currentBullet.transform.forward * 20, ForceMode.Impulse); // 依w行方向推送子
        //currentBullet.GetComponent<Rigidbody>().AddForce(PlayerCamera.transform.up * , ForceMode.Impulse);

        bulletsLeft--;    // A中的子p一，以下的法都是一拥囊馑
                          //bulletsLeft -= 1;               
                          //bulletsLeft = bulletsLeft - 1;  // 比^余碌法

        // 後座力模M
        this.GetComponent<Rigidbody>().AddForce(-shootingDirection.normalized * recoilForce, ForceMode.Impulse);

        ShowAmmoDisplay();                 // 更新量@示

        animatorObject.SetTrigger("Fire");  // |l「Fire」的|l
    }

    // 方法：QA的延trgO定
    private void Reload()
    {
        reloading = true;                      // 首先QABO定椋赫在QA
        reloadingDisplay.enabled = true;       // ⒄在QA的字幕@示出
        Invoke("ReloadFinished", reloadTime);  // 依照reloadTime所O定的QArg倒担rg0r绦ReloadFinished方法
    }

    // 方法：QA
    private void ReloadFinished()
    {
        bulletsLeft = magazineSize;            // ⒆填M
        reloading = false;                     // QABO定椋焊QAY束
        reloadingDisplay.enabled = false;      // ⒄在QA的字幕[藏，Y束QA的幼
        ShowAmmoDisplay();
    }

    // 方法：更新量@示
    private void ShowAmmoDisplay()
    {
        if (ammunitionDisplay != null)
            ammunitionDisplay.SetText($"Ammo {bulletsLeft} / {magazineSize}");
    }
}
